annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/lukas-pastva/helm-snowplow
    - name: Upstream Project
      url: https://github.com/lukas-pastva/helm-snowplow
  artifacthub.io/operator: "true"
apiVersion: v2
appVersion: v1.1
description: helm-snowplow Snowplow k8s chart
home: https://github.com/lukas-pastva/helm-snowplow
keywords:
  - argocd
kubeVersion: '>=1.16.0-0'
maintainers:
  - email: info@lukaspastva.sk
    name: lukas-pastva
name: helm-snowplow
sources:
  - https://github.com/lukas-pastva/helm-snowplow
type: application
version: 0.1.40