nameOverride: ""

collectorServiceaccountCreds: "ZW1wdHkK"
enrichServiceaccountCreds: "ZW1wdHkK"
bqloaderServiceaccountCreds: "ZW1wdHkK"
igluApiKey: "5B2B71B8-B1D7-46DA-BA39-54D583558E23"
igluDatabaseHost: "iglu-rw.svc.cluster.local"
igluDatabase: "iglu"
igluDatabaseUser: "aWdsdQ=="
igluDatabasePassword: "aWdsdQ=="
igluDatabaseMasterUser: "bWFzdGVy"
igluDatabaseMasterPassword: "bWFzdGVy"
googleProjectId: "empty"
enrichSalt: "empty"
yourProjectId: "empty"