nameOverride: ""

url: "snowplow.com"
akhqUrl: "akhq.com"

collector:
  serviceaccountCreds: "ZW1wdHkK"
  kafka:
    outTopic: collector-payloads
  serviceType: NodePort

enrich:
  serviceaccountCreds: "ZW1wdHkK"
  salt: "empty"

bqloader:
  serviceaccountCreds: "ZW1wdHkK"

iglu:
  apiKey: "5B2B71B8-B1D7-46DA-BA39-54D583558E23"
  database:
    host: "snowplow-postgres.snowplow"
    name: "iglu"
    user: "iglu"
    password: "iglu"
    masterUser: "postgres"
    masterPassword: "postgres"

streamloader:
  database:
    host: "snowplow-postgres.snowplow"
    name: "streamloader_db"
    user: "streamloader"
    password: "streamloader"
    masterUser: "postgres"
    masterPassword: "postgres"

postgresql:
  enabled: true
  nameOverride: postgres
  auth:
    postgresPassword: postgres
    username: iglu
    password: iglu
    database: iglu
  primary:
    resources:
      limits:
        cpu: 1000m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 128Mi
    persistence:
        size: 10Gi
    service:
      type: NodePort

pgAdmin:
  url: "postgre.snowplow.com"
  defaultEmail: 'postgres@email.com'
  defaultPassword: 'postgres'

strimzi:
  enabled: false
cloudnativepg:
  enabled: false