nameOverride: ""

collectorServiceaccountCreds: "ZW1wdHkK"
enrichServiceaccountCreds: "ZW1wdHkK"
bqloaderServiceaccountCreds: "ZW1wdHkK"
igluApiKey: "5B2B71B8-B1D7-46DA-BA39-54D583558E23"
igluDatabaseHost: "iglu-rw.snowplow.svc.cluster.local"
igluDatabase: "iglu"
igluDatabaseUser: "iglu"
igluDatabasePassword: "iglu"
igluDatabaseMasterUser: "master"
igluDatabaseMasterPassword: "master"
googleProjectId: "empty"
enrichSalt: "empty"
yourProjectId: "empty"