nameOverride: ""

collectorServiceaccountCreds: "ZW1wdHkK"
enrichServiceaccountCreds: "ZW1wdHkK"
bqloaderServiceaccountCreds: "ZW1wdHkK"
igluApiKey: "empty"
igluDatabase: "iglu"
igluDatabaseUser: "iglu"
igluDatabasePassword: "iglu"
googleProjectId: "empty"
enrichSalt: "empty"
yourProjectId: "empty"