nameOverride: ""

url: "snowplow.com"
streamloaderPostgreUrl: "postgre.snowplow.com"

collectorServiceaccountCreds: "ZW1wdHkK"
enrichServiceaccountCreds: "ZW1wdHkK"
bqloaderServiceaccountCreds: "ZW1wdHkK"
igluApiKey: "5B2B71B8-B1D7-46DA-BA39-54D583558E23"
igluDatabaseHost: "iglu-rw.snowplow.svc.cluster.local"

igluDatabase: "iglu"
igluDatabaseUser: "iglu"
igluDatabasePassword: "iglu"
igluDatabaseMasterUser: "postgres"
igluDatabaseMasterPassword: "master"

streamloaderDatabase: "streamloader"
streamloaderDatabaseEmail: "email@email.com"
streamloaderDatabaseUser: "streamloader"
streamloaderDatabasePassword: "streamloader"
streamloaderDatabaseMasterUser: "postgres"
streamloaderDatabaseMasterPassword: "master"

googleProjectId: "empty"
enrichSalt: "empty"
yourProjectId: "empty"