apiVersion: v1
kind: Service
metadata:
  name: akhq
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: akhq
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
