apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrich-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrich
  template:
    metadata:
      labels:
        app: enrich
        checksum-config: {{ include (print $.Template.BasePath "/enrich-cm.yml") . | sha256sum | trimSuffix "-" | trunc 63 }}
    spec:
      containers:
        - name: enrich-server
          image: snowplow/snowplow-enrich-pubsub:3.7.0
          command:
            - "/home/snowplow/bin/snowplow-enrich-pubsub"
            - "--config"
            - "/snowplow/config/config.hocon"
            - "--iglu-config"
            - "/snowplow/config/iglu-config.json"
            - "--enrichments"
            - "/snowplow/config/enrichments"
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: -Dorg.slf4j.simpleLogger.defaultLogLevel=info -Dorg.slf4j.simpleLogger.log.InvalidEnriched=debug
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/sa_credentials.json
          volumeMounts:
            - name: enrich-config-volume
              mountPath: /snowplow/config
            - name: service-account-credentials-volume
              mountPath: /etc/gcp
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "350m"
            limits:
              memory: "1.5Gi"
      volumes:
        - name: enrich-config-volume
          configMap:
            name: enrich-configmap
            items:
              - key: iglu-config.json
                path: iglu-config.json
              - key: config.hocon
                path: config.hocon
              - key: enrichment_campaigns.json
                path: enrichments/enrichment_campaigns.json
              - key: enrichment_pii.json
                path: enrichments/enrichment_pii.json
              - key: enrichment_event_fingerprint.json
                path: enrichments/enrichment_event_fingerprint.json
              - key: enrichment_referrer_parser.json
                path: enrichments/enrichment_referrer_parser.json
              - key: enrichment_ua_parser.json
                path: enrichments/enrichment_ua_parser.json
        - name: service-account-credentials-volume
          secret:
            secretName: enrich-serviceaccount-creds
            items:
              - key: sa_json
                path: sa_credentials.json
