{{/*apiVersion: v1*/}}
{{/*kind: Secret*/}}
{{/*metadata:*/}}
{{/*  name: enrich-serviceaccount-creds*/}}
{{/*  namespace: {{ .Release.Namespace }}*/}}
{{/*type: Opaque*/}}
{{/*data:*/}}
{{/*  sa_json: |*/}}
{{/*    {{ .Values.enrichServiceaccountCreds }}*/}}
