kind: ConfigMap
apiVersion: v1
metadata:
  name: iglu-configmap
  namespace: {{ .Release.Namespace }}
data:
  iglu-server.hocon: |
    {
      "repoServer": {
        "interface": "0.0.0.0",
        "port": 8080,
        "threadPool": "cached",
        "maxConnections": 2048
      },
      "database": {
        "type": "postgres",
        "host": "iglu",
        "port": 5432,
        "dbname": "{{ .Values.igluDatabase }}",
        "username": "{{ .Values.igluDatabaseUser }}",
        "password": "{{ .Values.igluDatabasePassword }}",
        "driver": "org.postgresql.Driver",
        "pool": {
          "type": "hikari",
          "maximumPoolSize": 5
        },
        "connectionPool": {
          "type": "fixed",
          "size": 4
        },
        "transactionPool": "cached"
      },
      "debug": false,
      "patchesAllowed": true,
      "superApiKey": "{{ .Values.igluApiKey }}"
    }
