---
apiVersion: v1
data:
  password: {{ .Values.iglu.database.password | b64enc }}
  username: {{ .Values.iglu.database.user | b64enc }}
kind: Secret
metadata:
  name: iglu-postgre-app
  namespace: {{ .Release.Namespace }}
type: Opaque
---
apiVersion: v1
data:
  username: {{ .Values.iglu.database.masterUser | b64enc }}
  password: {{ .Values.iglu.database.masterPassword | b64enc }}
kind: Secret
metadata:
  name: iglu-postgre-master
  namespace: {{ .Release.Namespace }}
type: Opaque

