{{ if .Values.cloudnativepg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: iglu
  namespace: {{ .Release.Namespace }}
spec:
  description: "Iglu cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:15.3
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  superuserSecret:
    name: iglu-postgre-master
  bootstrap:
    initdb:
      database: {{ .Values.iglu.database.name }}
      owner: {{ .Values.iglu.database.user }}
      secret:
        name: iglu-postgre-app
  postgresql:
    pg_hba:
      - local all {{ .Values.iglu.database.masterUser }} md5
      - local all {{ .Values.iglu.database.user }} md5
{{ end }}