apiVersion: v1
kind: Secret
metadata:
  name: iglu-postgre
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.igluDatabaseUser }}
  password: {{ .Values.igluDatabasePassword }}