apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: iglu
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  monitoring:
      enablePodMonitor: true
  superuserSecret:
    name: iglu-postgre-master
  bootstrap:
    initdb:
      database: {{ .Values.igluDatabase }}
      owner: {{ .Values.igluDatabase }}
      secret:
        name: iglu-postgre-app