apiVersion: v1
kind: Service
metadata:
  name: iglu-server-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: iglu
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
