---
apiVersion: v1
data:
  password: {{ .Values.igluDatabasePassword }}
  username: {{ .Values.igluDatabaseUser }}
kind: Secret
metadata:
  name: iglu-postgre-app
  namespace: {{ .Release.Namespace }}
type: Opaque
---
apiVersion: v1
data:
  password: {{ .Values.igluDatabaseMasterPassword }}
  username: {{ .Values.igluDatabaseMasterUser }}
kind: Secret
metadata:
  name: iglu-postgre-master
  namespace: {{ .Release.Namespace }}
type: Opaque

