---
apiVersion: v1
data:
  password: {{ .Values.igluDatabasePassword | b64enc }}
  username: {{ .Values.igluDatabaseUser | b64enc }}
kind: Secret
metadata:
  name: iglu-postgre-app
  namespace: {{ .Release.Namespace }}
type: Opaque
---
apiVersion: v1
data:
  username: {{ .Values.igluDatabaseMasterUser | b64enc }}
  password: {{ .Values.igluDatabaseMasterPassword | b64enc }}
kind: Secret
metadata:
  name: iglu-postgre-master
  namespace: {{ .Release.Namespace }}
type: Opaque

