---
apiVersion: v1
kind: Secret
metadata:
  name: iglu-postgre-master
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.igluDatabaseMasterUser }}
  password: {{ .Values.igluDatabaseMasterPassword }}
---
apiVersion: v1
data:
  password: {{ .Values.igluDatabasePassword }}
  username: {{ .Values.igluDatabaseUser }}
kind: Secret
metadata:
  name: iglu-postgre-app
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth