{{/*apiVersion: apps/v1*/}}
{{/*kind: Deployment*/}}
{{/*metadata:*/}}
{{/*  name: repeater-server*/}}
{{/*  namespace: {{ .Release.Namespace }}*/}}
{{/*spec:*/}}
{{/*  replicas: 1*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      app: repeater*/}}
{{/*  template:*/}}
{{/*    metadata:*/}}
{{/*      labels:*/}}
{{/*        app: repeater*/}}
{{/*    spec:*/}}
{{/*      containers:*/}}
{{/*        - name: repeater-server*/}}
{{/*          image: snowplow/snowplow-bigquery-repeater:1.6.4*/}}
{{/*          command:*/}}
{{/*            - "/home/snowplow/bin/snowplow-bigquery-repeater"*/}}
{{/*            - "--config"*/}}
{{/*            - "/snowplow/config/config.hocon"*/}}
{{/*            - "--resolver"*/}}
{{/*            - "/snowplow/config/iglu-config.json"*/}}
{{/*            - "--bufferSize=20"*/}}
{{/*            - "--timeout=20"*/}}
{{/*            - "--backoffPeriod=900"*/}}
{{/*          imagePullPolicy: IfNotPresent*/}}
{{/*          env:*/}}
{{/*            - name: JAVA_OPTS*/}}
{{/*              value: -Dorg.slf4j.simpleLogger.defaultLogLevel=info*/}}
{{/*            - name: GOOGLE_APPLICATION_CREDENTIALS*/}}
{{/*              value: /etc/gcp/sa_credentials.json*/}}
{{/*          volumeMounts:*/}}
{{/*            - name: repeater-config-volume*/}}
{{/*              mountPath: /snowplow/config*/}}
{{/*            - name: service-account-credentials-volume*/}}
{{/*              mountPath: /etc/gcp*/}}
{{/*              readOnly: true*/}}
{{/*          resources:*/}}
{{/*            requests:*/}}
{{/*              memory: "128Mi"*/}}
{{/*              cpu: "150m"*/}}
{{/*            limits:*/}}
{{/*              memory: "512Mi"*/}}
{{/*      volumes:*/}}
{{/*        - name: repeater-config-volume*/}}
{{/*          configMap:*/}}
{{/*            name: streamloader-configmap*/}}
{{/*            items:*/}}
{{/*              - key: iglu-config.json*/}}
{{/*                path: iglu-config.json*/}}
{{/*              - key: config.hocon*/}}
{{/*                path: config.hocon*/}}
{{/*        - name: service-account-credentials-volume*/}}
{{/*          secret:*/}}
{{/*            secretName: bqloader-serviceaccount-creds*/}}
{{/*            items:*/}}
{{/*              - key: sa_json*/}}
{{/*                path: sa_credentials.json*/}}
