apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamloader-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamloader
  template:
    metadata:
      labels:
        app: streamloader
        checksum-config: {{ include (print $.Template.BasePath "/streamloader-cm.yaml") . | sha256sum | trimSuffix "-" | trunc 63 }}
    spec:
      containers:
        - name: streamloader-server
          image: snowplow/snowplow-postgres-loader:0.3.3
          command:
            - "/home/snowplow/bin/snowplow-postgres-loader"
            - "--config"
            - "/snowplow/config/config.hocon"
            - "--resolver"
            - "/snowplow/config/iglu-config.json"
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: -Dorg.slf4j.simpleLogger.defaultLogLevel=info
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/sa_credentials.json
          volumeMounts:
            - name: streamloader-config-volume
              mountPath: /snowplow/config
            - name: service-account-credentials-volume
              mountPath: /etc/gcp
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
      volumes:
        - name: streamloader-config-volume
          configMap:
            name: streamloader-configmap
            items:
              - key: iglu-config.json
                path: iglu-config.json
              - key: config.hocon
                path: config.hocon
        - name: service-account-credentials-volume
          secret:
            secretName: bqloader-serviceaccount-creds
            items:
              - key: sa_json
                path: sa_credentials.json
