kind: ConfigMap
apiVersion: v1
metadata:
  name: streamloader-configmap
  namespace: {{ .Release.Namespace }}
data:
  config.hocon: |
    {
      "input": {
        "type": "PubSub"
        "projectId": "my-project"
        "subscriptionId": "my-subscription"
      }

      "output" : {
        "good": {
          "type": "Postgres"
          "host": "{{ .Values.streamloader.database.host }}"
          "database": "{{ .Values.streamloader.database.name }}"
          "username": "{{ .Values.streamloader.database.user }}"
          "password": {{ .Values.streamloader.database.password }}
          "schema": "public"
          {{ if .Values.postgresql.enabled }}
          "sslMode": "disable"
          {{ end }}
        }
      }
    }
  iglu-config.json: |
    {
      "schema": "iglu:com.snowplowanalytics.iglu/resolver-config/jsonschema/1-0-3",
      "data": {
        "cacheSize": 500,
        "cacheTtl": 600,
        "repositories": [
          {
            "connection": {
              "http": {
                "uri": "http://iglucentral.com"
              }
            },
            "name": "Iglu Central",
            "priority": 10,
            "vendorPrefixes": []
          },
          {
            "connection": {
              "http": {
                "uri": "http://mirror01.iglucentral.com"
              }
            },
            "name": "Iglu Central - Mirror 01",
            "priority": 20,
            "vendorPrefixes": []
          },
          {
            "connection": {
              "http": {
                "apikey": "{{ .Values.iglu.apiKey }}",
                "uri": "http://iglu-server.snowplow.svc.cluster.local/api"
              }
            },
            "name": "Iglu Server",
            "priority": 0,
            "vendorPrefixes": []
          }
        ]
      }
    }
