{{ if .Values.cloudnativepg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: streamloader
  namespace: {{ .Release.Namespace }}
spec:
  description: "streamloader cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:15.3
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  superuserSecret:
    name: streamloader-postgre-master
  bootstrap:
    initdb:
      database: {{ .Values.streamloader.database.name }}
      owner: {{ .Values.streamloader.database.user }}
      secret:
        name: streamloader-postgre-app
  postgresql:
    pg_hba:
      - local all {{ .Values.streamloader.database.masterUser }} md5
      - local all {{ .Values.streamloader.database.user }} md5
{{ end }}