apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamloader-postgre-pgamin
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamloader-postgre-pgamin
  template:
    metadata:
      labels:
        app: streamloader-postgre-pgamin
    spec:
      containers:
        - name: streamloader-postgre-pgamin
          image: dpage/pgadmin4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
              protocol: TCP