apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamloader-postgre
  namespace: {{ .Release.Namespace }}
spec:
  tls:
    - hosts:
        - {{ .Values.streamloaderPostgreUrl }}
  rules:
    - host: {{ .Values.streamloaderPostgreUrl }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: collector
                port:
                  number: 8080
