apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamloader-postgre-pgamin
  namespace: {{ .Release.Namespace }}
spec:
  tls:
    - hosts:
        - {{ .Values.pgAdmin.url }}
  rules:
    - host: {{ .Values.pgAdmin.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: streamloader-postgre-pgamin
                port:
                  number: 80
