---
apiVersion: v1
data:
  password: {{ .Values.streamloaderDatabasePassword | b64enc }}
  username: {{ .Values.streamloaderDatabaseUser | b64enc }}
kind: Secret
metadata:
  name: streamloader-postgre-app
  namespace: {{ .Release.Namespace }}
type: Opaque
---
apiVersion: v1
data:
  username: {{ .Values.streamloaderDatabaseMasterUser | b64enc }}
  password: {{ .Values.streamloaderDatabaseMasterPassword | b64enc }}
kind: Secret
metadata:
  name: streamloader-postgre-master
  namespace: {{ .Release.Namespace }}
type: Opaque

