apiVersion: v1
kind: Secret
metadata:
  name: bqloader-serviceaccount-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  sa_json: |
    <base64-string-of-bqloader-service-account-key-file>
